name: GitHub Actions Demo
run-name: ${{ github.actor }} Testing again
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
      -  run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "Goedemorgen"
      - name: Setup PHP with PECL extension 
        uses: shivammathur/setup-php@v2
        with:
        php-version: '8.3'
      - run: npx playwright install
      - run: npx playwright test